### ISSUE TITLE
Automatically alphabetise source file in an async job

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkiverse-docs#161]
We often have to give feedback on PRs asking people to put things in alphabetical order. See, for example, https://github.com/quarkiverse/quarkiverse-docs/pull/160#discussion_r1624473116. 

We could reduce friction for contributors and effort for us if we had a CI job to sort out the order and commit back corrections.

**Comment by gastaldi** [comment]
That's a good idea

**Comment by holly-cummins** [comment]
Reminded of this by https://github.com/quarkiverse/quarkiverse-docs/pull/171#issuecomment-2271111454 :)

**Comment by gastaldi** [comment]
Instead of doing it in an async job, wouldn't be better if it performed this validation when the PR is opened?

**Comment by holly-cummins** [comment]
I think something that happened when the PR was opened could mark the PR red, but not fix the problem. So that would be a better experience for us, and faster feedback for extension authors, but we'd still be knocking their contributions back and asking them to manually do what a computer could do. 

On the other hand, it avoids all the scariness of automated changes, and it would be easy to do.

**Comment by holly-cummins** [comment]
https://github.com/orgs/community/discussions/24945 seems to imply that commits can be added to someone else's PR, and provides an action for it. So maybe it *is* possible, in which case we should ignore all my comments above. :)
